; PlatformIO Project Configuration
; Board: ESP32 Dev Module + LoRa SX1278 (sender)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3

lib_deps =
    sandeepmistry/LoRa@^0.8.0